FROM oven/bun:1

WORKDIR /app

# Install dependencies
# We copy only package.json and bun.lock for cache efficiency
COPY package.json bun.lock ./
RUN bun install

# Copy source files
COPY . .

EXPOSE 3005

CMD ["bun", "run", "dev", "-p", "3005"]
